# Generated by Django 5.1.1 on 2024-11-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_group_grouppost_page_pagepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='like',
        ),
        migrations.RemoveField(
            model_name='page',
            name='like',
        ),
    ]
