# Generated by Django 5.1.1 on 2024-11-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='grouppost',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='pagepost',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
